Register email required test
radumarinoiu/DSC-QA-Frontend-TestingTool pull request #45
Opened 2020-05-07 19:04 UTC by davidviziteu

task done, tested, working

2020-05-08 10:13 UTC, radumarinoiu requested changes
Scenariul functioneaza cum ar trebui, doar ca are prea multi pasi care nu fac nimic :)
Gj :+1:

2020-05-08 10:13 UTC, radumarinoiu commented on TestingTool/tests/register_email_dsc_required.json
> +      "name": "click first name field (random element from webpage)",
Mai scoate te rog din pasi, sunt inutili si doar 'consuma timp' fara nici-un rost :))
E nevoie de un 'proof of concept' minimal doar

2020-05-08 10:31 UTC, davidviziteu commented on TestingTool/tests/register_email_dsc_required.json
> +      "name": "click first name field (random element from webpage)",
am scos si am facut un nou pr

2020-05-08 10:32 UTC, davidviziteu commented
am mai scos pasi

2020-05-13 18:33 UTC, radumarinoiu approved these changes

2020-05-13 18:33 UTC, merged